const $ = (id) => document.getElementById(id);
const PAPER = { A4: [210, 297], A5: [148, 210], B5: [176, 250] };
const MAX_HISTORY = 30;
let pages = [], currentPage = 0, mode = 'blank', history = [], future = [];
let selectedId = null, editingTextId = null, drag = null, cropMode = false, cropStart = null, cropRect = null, sliderHistoryStarted = false;
let dialogStyle = { bold:false, italic:false, underline:false, vertical:false, align:'left' };
const uid = () => crypto.randomUUID ? crypto.randomUUID() : `${Date.now()}-${Math.random()}`;
const clone = (v) => JSON.parse(JSON.stringify(v));
const blankPage = () => ({ id:uid(), source:null, sourceName:'白紙', background:false, rotation:0, scale:1, brightness:100, contrast:100, grayscale:false, paper:'A4', orientation:'portrait', elements:[] });
const snapshot = () => ({ pages:clone(pages), currentPage, mode });
function pushHistory(){ history.push(snapshot()); if(history.length>MAX_HISTORY) history.shift(); future=[]; updateHistoryButtons(); }
function updateHistoryButtons(){ $('undoButton').disabled=!history.length; $('redoButton').disabled=!future.length; }
function restore(state){ pages=clone(state.pages); currentPage=Math.min(Math.max(0,state.currentPage),Math.max(0,pages.length-1)); mode=state.mode; selectedId=null; render(); }
function dims(p){ const [w,h]=PAPER[p.paper]||PAPER.A4; return p.orientation==='portrait'?[w,h]:[h,w]; }
function aspect(p){ const [w,h]=dims(p); return `${w}/${h}`; }
function refreshControls(){ const p=pages[currentPage]; if(!p)return; $('paperSize').value=p.paper; $('orientation').value=p.orientation; $('scaleRange').value=Math.round(p.scale*100); $('scaleLabel').textContent=`${Math.round(p.scale*100)}%`; $('brightnessRange').value=p.brightness; $('contrastRange').value=p.contrast; $('grayscaleButton').textContent=p.grayscale?'🟦 カラーに戻す':'⚫ 白黒にする'; $('pageIndicator').textContent=`${currentPage+1} / ${pages.length}`; $('prevPageButton').disabled=currentPage===0; $('nextPageButton').disabled=currentPage===pages.length-1; updateSelectionUI(); updateHistoryButtons(); }
function updateSelectionUI(){ const item=pages[currentPage]?.elements.find(e=>e.id===selectedId); $('editSelectedButton').disabled=item?.type!=='text'; $('deleteSelectedButton').disabled=!item; }
function render(){ const p=pages[currentPage]; if(!p)return; const layer=$('documentLayer'); layer.innerHTML=''; layer.style.aspectRatio=aspect(p); $('pageArea').style.aspectRatio=aspect(p); if(p.source){ const img=document.createElement('img'); img.className='page-background'; img.src=p.source; img.style.filter=`brightness(${p.brightness}%) contrast(${p.contrast}%)${p.grayscale?' grayscale(100%)':''}`; img.style.transform=`scale(${p.scale}) rotate(${p.rotation}deg)`; layer.appendChild(img); } p.elements.forEach(item=>layer.appendChild(makeElement(item))); refreshControls(); $('printButton').disabled=!pages.length; $('previewButton').disabled=!pages.length; }
function makeElement(item){ const el=document.createElement('div'); el.className=`canvas-item ${item.type} ${item.id===selectedId?'selected':''}`; el.dataset.id=item.id; el.style.left=`${item.x*100}%`; el.style.top=`${item.y*100}%`; el.style.width=`${item.w*100}%`; el.style.height=`${item.h*100}%`; if(item.type==='text'){ el.textContent=item.value; el.style.fontSize=`${item.size}px`; el.style.color=item.color; el.style.fontWeight=item.bold?'800':'500'; el.style.fontStyle=item.italic?'italic':'normal'; el.style.textDecoration=item.underline?'underline':'none'; el.style.writingMode=item.vertical?'vertical-rl':'horizontal-tb'; el.style.textAlign=item.align||'left'; } else { const img=document.createElement('img'); img.src=item.src; img.draggable=false; el.appendChild(img); } const handle=document.createElement('span'); handle.className='resize-handle'; el.appendChild(handle); el.addEventListener('pointerdown',e=>{ if(cropMode)return; e.preventDefault(); e.stopPropagation(); selectedId=item.id; drag={item,startX:e.clientX,startY:e.clientY,x:item.x,y:item.y,w:item.w,h:item.h,resize:e.target===handle,before:snapshot()}; el.setPointerCapture(e.pointerId); updateSelectionUI(); }); el.addEventListener('pointermove',e=>{ if(!drag||drag.item!==item)return; const r=$('documentLayer').getBoundingClientRect(); const dx=(e.clientX-drag.startX)/r.width, dy=(e.clientY-drag.startY)/r.height; if(drag.resize){ item.w=Math.max(.05,Math.min(.95,drag.w+dx)); item.h=Math.max(.04,Math.min(.95,drag.h+dy)); } else { item.x=Math.max(0,Math.min(.95,drag.x+dx)); item.y=Math.max(0,Math.min(.95,drag.y+dy)); } el.style.left=`${item.x*100}%`; el.style.top=`${item.y*100}%`; el.style.width=`${item.w*100}%`; el.style.height=`${item.h*100}%`; }); const end=()=>{ if(!drag||drag.item!==item)return; history.push(drag.before); if(history.length>MAX_HISTORY)history.shift(); future=[]; drag=null; updateHistoryButtons(); }; el.addEventListener('pointerup',end); el.addEventListener('pointercancel',end); el.addEventListener('dblclick',e=>{e.stopPropagation(); if(item.type==='text')openTextDialog(item);}); return el; }
function enterEditor(which){ mode=which; $('homeScreen').classList.add('hidden'); $('editor').classList.remove('hidden'); if(!pages.length)pages=[blankPage()]; history=[]; future=[]; currentPage=0; selectedId=null; render(); }
function loadImage(file){ return new Promise((resolve,reject)=>{ const r=new FileReader(); r.onload=()=>resolve(r.result); r.onerror=reject; r.readAsDataURL(file); }); }
async function loadFile(file){ try { if(file.type.startsWith('image/')){ pages=[{...blankPage(),source:await loadImage(file),sourceName:file.name,background:true}]; mode='scan'; currentPage=0; history=[]; future=[]; selectedId=null; enterEditor('scan'); return; } if(file.type==='application/pdf'||file.name.toLowerCase().endsWith('.pdf')){ const pdfjs=await import('https://cdnjs.cloudflare.com/ajax/libs/pdf.js/4.10.38/pdf.min.mjs'); pdfjs.GlobalWorkerOptions.workerSrc='https://cdnjs.cloudflare.com/ajax/libs/pdf.js/4.10.38/pdf.worker.min.mjs'; const pdf=await pdfjs.getDocument({data:await file.arrayBuffer()}).promise; const out=[]; for(let i=1;i<=pdf.numPages;i++){ const pg=await pdf.getPage(i); const v=pg.getViewport({scale:1.5}); const c=document.createElement('canvas'); c.width=Math.ceil(v.width); c.height=Math.ceil(v.height); await pg.render({canvasContext:c.getContext('2d'),viewport:v}).promise; out.push({...blankPage(),source:c.toDataURL('image/png'),sourceName:`${file.name} - ${i}ページ`,background:true}); } if(!out.length){alert('PDFにページがありません。');return;} pages=out; mode='scan'; currentPage=0; history=[]; future=[]; selectedId=null; enterEditor('scan'); return; } alert('画像またはPDFを選んでください。'); } catch(e){ console.error(e); alert(`ファイルを開けませんでした。\n${e.message||''}`); } }
$('scanModeButton').addEventListener('click',()=>$('fileInput').click()); $('blankModeButton').addEventListener('click',()=>{pages=[blankPage()];enterEditor('blank');}); $('homeHelpButton').addEventListener('click',openHelp); $('helpButton').addEventListener('click',openHelp); $('closeHelpButton').addEventListener('click',closeHelp); function openHelp(){$('helpDialog').classList.remove('hidden');} function closeHelp(){$('helpDialog').classList.add('hidden');}
$('fileInput').addEventListener('change',()=>{const f=$('fileInput').files[0];if(f)loadFile(f);}); $('openFileButton').addEventListener('click',()=>$('fileInput').click()); $('backHomeButton').addEventListener('click',()=>{exitCropMode();closePreview();closeTextDialog();$('editor').classList.add('hidden');$('homeScreen').classList.remove('hidden');});
function addBlankPageFromCurrent(){const current=pages[currentPage]||blankPage();pushHistory();pages.push({...blankPage(),paper:current.paper,orientation:current.orientation});currentPage=pages.length-1;mode='blank';render();}
$('newBlankButton').addEventListener('click',addBlankPageFromCurrent); $('addPageButton').addEventListener('click',addBlankPageFromCurrent);
$('prevPageButton').addEventListener('click',()=>{if(currentPage>0){currentPage--;selectedId=null;render();}}); $('nextPageButton').addEventListener('click',()=>{if(currentPage<pages.length-1){currentPage++;selectedId=null;render();}});
$('paperSize').addEventListener('change',e=>{if(!pages.length)return;pushHistory();pages[currentPage].paper=e.target.value;render();}); $('orientation').addEventListener('change',e=>{if(!pages.length)return;const next=e.target.value;if(next===pages[currentPage].orientation)return;pushHistory();pages[currentPage].orientation=next;render();}); $('rotatePageButton').addEventListener('click',()=>{if(!pages.length)return;pushHistory();pages[currentPage].orientation=pages[currentPage].orientation==='portrait'?'landscape':'portrait';render();});
function startSliderHistory(){if(!sliderHistoryStarted&&pages.length){pushHistory();sliderHistoryStarted=true;}} function endSliderHistory(){sliderHistoryStarted=false;}
for(const id of ['scaleRange','brightnessRange','contrastRange'])$(id).addEventListener('pointerdown',startSliderHistory); for(const id of ['scaleRange','brightnessRange','contrastRange'])$(id).addEventListener('input',e=>{if(!pages.length)return;const p=pages[currentPage];if(id==='scaleRange')p.scale=Number(e.target.value)/100;if(id==='brightnessRange')p.brightness=Number(e.target.value);if(id==='contrastRange')p.contrast=Number(e.target.value);if(id==='scaleRange')$('scaleLabel').textContent=`${e.target.value}%`;render();}); window.addEventListener('pointerup',endSliderHistory);
$('grayscaleButton').addEventListener('click',()=>{if(!pages.length)return;pushHistory();pages[currentPage].grayscale=!pages[currentPage].grayscale;render();});
$('addTextButton').addEventListener('click',()=>openTextDialog()); $('addImageButton').addEventListener('click',()=>$('imageInput').click()); $('imageInput').addEventListener('change',async()=>{const f=$('imageInput').files[0];if(!f)return;try{const src=await loadImage(f);pushHistory();pages[currentPage].elements.push({id:uid(),type:'image',src,x:.1,y:.1,w:.42,h:.3});selectedId=null;render();}catch(e){alert('画像を読み込めませんでした。')}finally{$('imageInput').value='';}});
$('deleteSelectedButton').addEventListener('click',()=>{if(!selectedId)return;const p=pages[currentPage];if(!p.elements.some(e=>e.id===selectedId))return;pushHistory();p.elements=p.elements.filter(e=>e.id!==selectedId);selectedId=null;render();}); $('editSelectedButton').addEventListener('click',()=>{const item=pages[currentPage].elements.find(e=>e.id===selectedId);if(item?.type==='text')openTextDialog(item);}); $('undoButton').addEventListener('click',()=>{if(!history.length)return;future.push(snapshot());restore(history.pop());}); $('redoButton').addEventListener('click',()=>{if(!future.length)return;history.push(snapshot());restore(future.pop());});
document.addEventListener('keydown',e=>{const typing=['INPUT','TEXTAREA','SELECT'].includes(e.target?.tagName);if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='z'&&!typing){e.preventDefault();$('undoButton').click();}if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='y'&&!typing){e.preventDefault();$('redoButton').click();}if(e.key==='Delete'&&!typing)$('deleteSelectedButton').click();if(e.key==='Escape'){closeHelp();closeTextDialog();closePreview();exitCropMode();}});
function openTextDialog(item=null){editingTextId=item?.id||null;dialogStyle={bold:item?.bold||false,italic:item?.italic||false,underline:item?.underline||false,vertical:item?.vertical||false,align:item?.align||'left'};$('textInput').value=item?.value||'';$('textSize').value=item?.size||28;$('textColor').value=item?.color||'#111111';syncDialogButtons();updateTextPreview();$('textDialog').classList.remove('hidden');requestAnimationFrame(()=>$('textInput').focus());} function closeTextDialog(){$('textDialog').classList.add('hidden');editingTextId=null;} function syncDialogButtons(){$('boldTextButton').classList.toggle('active',dialogStyle.bold);$('italicTextButton').classList.toggle('active',dialogStyle.italic);$('underlineTextButton').classList.toggle('active',dialogStyle.underline);$('verticalTextButton').classList.toggle('active',dialogStyle.vertical);document.querySelectorAll('[data-align]').forEach(b=>b.classList.toggle('active',b.dataset.align===dialogStyle.align));} function updateTextPreview(){const e=$('textPreview');if(!e)return;e.textContent=$('textInput').value||'入力した文字がここに表示されます';e.style.fontSize=`${$('textSize').value}px`;e.style.color=$('textColor').value;e.style.fontWeight=dialogStyle.bold?'800':'500';e.style.fontStyle=dialogStyle.italic?'italic':'normal';e.style.textDecoration=dialogStyle.underline?'underline':'none';e.style.writingMode=dialogStyle.vertical?'vertical-rl':'horizontal-tb';e.style.textAlign=dialogStyle.align;}
$('textInput').addEventListener('input',updateTextPreview);$('textSize').addEventListener('input',updateTextPreview);$('textColor').addEventListener('input',updateTextPreview);for(const[id,key]of[['boldTextButton','bold'],['italicTextButton','italic'],['underlineTextButton','underline'],['verticalTextButton','vertical']])$(id).addEventListener('click',()=>{dialogStyle[key]=!dialogStyle[key];syncDialogButtons();updateTextPreview();});document.querySelectorAll('[data-align]').forEach(b=>b.addEventListener('click',()=>{dialogStyle.align=b.dataset.align;syncDialogButtons();updateTextPreview();})); $('cancelText').addEventListener('click',closeTextDialog); $('confirmText').addEventListener('click',()=>{const value=$('textInput').value.trim();if(!value||!pages.length)return;pushHistory();const p=pages[currentPage];if(editingTextId){const item=p.elements.find(e=>e.id===editingTextId);if(item)Object.assign(item,{value,size:Number($('textSize').value),color:$('textColor').value,...dialogStyle});}else{const item={id:uid(),type:'text',value,size:Number($('textSize').value),color:$('textColor').value,x:.06,y:.06,w:.62,h:.18,...dialogStyle};p.elements.push(item);selectedId=item.id;}closeTextDialog();render();});
$('cropButton').addEventListener('click',enterCropMode); $('cancelCropButton').addEventListener('click',exitCropMode); $('applyCropButton').addEventListener('click',applyCrop);
function enterCropMode(){const page=pages[currentPage];if(!page?.source){alert('画像やPDFを開いているページで使えます。');return;}if(page.scale!==1||page.rotation!==0){pushHistory();page.scale=1;page.rotation=0;render();}cropMode=true;cropStart=null;cropRect=null;$('cropNotice').classList.remove('hidden');$('cropOverlay').classList.remove('hidden');}
function exitCropMode(){cropMode=false;cropStart=null;cropRect=null;$('cropNotice').classList.add('hidden');$('cropOverlay').classList.add('hidden');updateCropOverlay();}
function layerPoint(e){const r=$('documentLayer').getBoundingClientRect();return{x:Math.max(0,Math.min(1,(e.clientX-r.left)/r.width)),y:Math.max(0,Math.min(1,(e.clientY-r.top)/r.height))};}
$('pageArea').addEventListener('pointerdown',e=>{if(!cropMode||e.target.closest('.canvas-item'))return;cropStart=layerPoint(e);cropRect={x:cropStart.x,y:cropStart.y,w:0,h:0};$('pageArea').setPointerCapture?.(e.pointerId);updateCropOverlay();}); $('pageArea').addEventListener('pointermove',e=>{if(!cropMode||!cropStart)return;const p=layerPoint(e);cropRect={x:Math.min(cropStart.x,p.x),y:Math.min(cropStart.y,p.y),w:Math.abs(cropStart.x-p.x),h:Math.abs(cropStart.y-p.y)};updateCropOverlay();}); $('pageArea').addEventListener('pointerup',()=>{if(cropMode)cropStart=null;}); $('pageArea').addEventListener('pointercancel',()=>{cropStart=null;}); function updateCropOverlay(){const o=$('cropOverlay');if(!cropRect){o.style.width='0';o.style.height='0';return;}o.style.left=`${cropRect.x*100}%`;o.style.top=`${cropRect.y*100}%`;o.style.width=`${cropRect.w*100}%`;o.style.height=`${cropRect.h*100}%`;}
async function applyCrop(){const p=pages[currentPage];if(!p?.source||!cropRect||cropRect.w<.03||cropRect.h<.03){alert('切り取る範囲をドラッグしてください。');return;}try{pushHistory();const img=await new Promise((resolve,reject)=>{const i=new Image();i.onload=()=>resolve(i);i.onerror=reject;i.src=p.source;});const sx=Math.round(img.naturalWidth*cropRect.x),sy=Math.round(img.naturalHeight*cropRect.y),sw=Math.max(1,Math.round(img.naturalWidth*cropRect.w)),sh=Math.max(1,Math.round(img.naturalHeight*cropRect.h));const c=document.createElement('canvas');c.width=sw;c.height=sh;c.getContext('2d').drawImage(img,sx,sy,sw,sh,0,0,sw,sh);p.source=c.toDataURL('image/png');p.sourceName=`${p.sourceName}（切り取り後）`;p.scale=1;p.rotation=0;exitCropMode();render();}catch(e){alert('切り取りに失敗しました。');}}
$('previewButton').addEventListener('click',openPreview);$('closePreviewButton').addEventListener('click',closePreview);$('previewPrintButton').addEventListener('click',printAll); function closePreview(){$('previewDialog').classList.add('hidden');} function buildPaper(p){const sheet=document.createElement('div');sheet.className='paper-sheet';const[w,h]=dims(p);sheet.style.aspectRatio=`${w}/${h}`;sheet.style.width=`${w}mm`;sheet.style.height=`${h}mm`;if(p.source){const img=document.createElement('img');img.className='paper-bg';img.src=p.source;img.style.filter=`brightness(${p.brightness}%) contrast(${p.contrast}%)${p.grayscale?' grayscale(100%)':''}`;img.style.transform=`scale(${p.scale}) rotate(${p.rotation}deg)`;sheet.appendChild(img);}for(const item of p.elements){const el=document.createElement('div');el.className=`paper-item ${item.type}`;el.style.left=`${item.x*100}%`;el.style.top=`${item.y*100}%`;el.style.width=`${item.w*100}%`;el.style.height=`${item.h*100}%`;if(item.type==='text'){el.textContent=item.value;el.style.fontSize=`${item.size}px`;el.style.color=item.color;el.style.fontWeight=item.bold?'800':'500';el.style.fontStyle=item.italic?'italic':'normal';el.style.textDecoration=item.underline?'underline':'none';el.style.writingMode=item.vertical?'vertical-rl':'horizontal-tb';el.style.textAlign=item.align||'left';}else{const img=document.createElement('img');img.src=item.src;el.appendChild(img);}sheet.appendChild(el);}return sheet;}
function openPreview(){const root=$('previewPages');root.innerHTML='';pages.forEach(p=>root.appendChild(buildPaper(p)));$('previewDialog').classList.remove('hidden');} function printAll(){const root=document.createElement('div');root.id='printRoot';pages.forEach(p=>root.appendChild(buildPaper(p)));document.body.appendChild(root);requestAnimationFrame(()=>requestAnimationFrame(()=>window.print()));const cleanup=()=>{root.remove();window.removeEventListener('afterprint',cleanup);};window.addEventListener('afterprint',cleanup);setTimeout(()=>{if(root.isConnected)root.remove();window.removeEventListener('afterprint',cleanup);},5000);}
document.addEventListener('dragover',e=>e.preventDefault());document.addEventListener('drop',e=>e.preventDefault()); pages=[]; $('printButton').disabled=true; $('previewButton').disabled=true; updateHistoryButtons(); $('editor').classList.add('hidden'); $('homeScreen').classList.remove('hidden');